// Code generated by MockGen. DO NOT EDIT.
// Source: runner.go
//
// Package mock_runner is a generated GoMock package.
package mock_runner

import (
	context "context"
	io "io"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockRunner is a mock of Runner interface.
type MockRunner struct {
	ctrl     *gomock.Controller
	recorder *MockRunnerMockRecorder
}

// MockRunnerMockRecorder is the mock recorder for MockRunner.
type MockRunnerMockRecorder struct {
	mock *MockRunner
}

// NewMockRunner creates a new mock instance.
func NewMockRunner(ctrl *gomock.Controller) *MockRunner {
	mock := &MockRunner{ctrl: ctrl}
	mock.recorder = &MockRunnerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRunner) EXPECT() *MockRunnerMockRecorder {
	return m.recorder
}

// Env mocks base method.
func (m *MockRunner) Env(env ...string) {
	m.ctrl.T.Helper()
	varargs := []any{}
	for _, a := range env {
		varargs = append(varargs, a)
	}
	m.ctrl.Call(m, "Env", varargs...)
}

// Env indicates an expected call of Env.
func (mr *MockRunnerMockRecorder) Env(env ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Env", reflect.TypeOf((*MockRunner)(nil).Env), env...)
}

// Run mocks base method.
func (m *MockRunner) Run(stdin io.Reader, stdout, stderr io.Writer, command string, args ...string) error {
	m.ctrl.T.Helper()
	varargs := []any{stdin, stdout, stderr, command}
	for _, a := range args {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Run", varargs...)
	ret0, _ := ret[0].(error)
	return ret0
}

// Run indicates an expected call of Run.
func (mr *MockRunnerMockRecorder) Run(stdin, stdout, stderr, command any, args ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{stdin, stdout, stderr, command}, args...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Run", reflect.TypeOf((*MockRunner)(nil).Run), varargs...)
}

// RunContext mocks base method.
func (m *MockRunner) RunContext(ctx context.Context, stdin io.Reader, stdout, stderr io.Writer, command string, args ...string) error {
	m.ctrl.T.Helper()
	varargs := []any{ctx, stdin, stdout, stderr, command}
	for _, a := range args {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "RunContext", varargs...)
	ret0, _ := ret[0].(error)
	return ret0
}

// RunContext indicates an expected call of RunContext.
func (mr *MockRunnerMockRecorder) RunContext(ctx, stdin, stdout, stderr, command any, args ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, stdin, stdout, stderr, command}, args...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RunContext", reflect.TypeOf((*MockRunner)(nil).RunContext), varargs...)
}
